 const SET_INITIAL_INGREDIENTS="SET_INITIAL_INGREDIENTS";
 const SET_NEW_TOTAL_PRICE="SET_NEW_TOTAL_PRICE"
 const ADD_INGREDIENT="ADD_INGREDIENT"
 const REMOVE_INGREDIENT="REMOVE_INGREDIENT"


 const SET_USER_AUTH="SET_USER_AUTH";
 const LOGOUT="LOGOUT"
 

 export {
    SET_INITIAL_INGREDIENTS  ,
    SET_NEW_TOTAL_PRICE,
    ADD_INGREDIENT,
    REMOVE_INGREDIENT,
    SET_USER_AUTH,
    LOGOUT

 }